### ISSUE TITLE
ldriveskier forum request

### ISSUE THREAD

**Issue by jm6087** [SkiDooGuy/WME-Road-Shield-Assistant#5]
Postby ldriveskier (profile) » Thu Apr 29, 2021 6:38 am

Can you please only highlight if the route number being shielded is the only thing on the segment? With the addition of the ramp highlighting, almost every single ramp segment now glows. Everything from a simple "to I-90 W" to more complex names are highlighted. Also, roads that are "Old US-42" were already being highlighted and shouldn't be. Thank you!

ETA: Clearly, if there is a directional on the route name, that should stay. Eg, "90 W" should be highlighted, but "to 90 W" or "Exit 5: 90 W » Cleveland" should not be highlighted.

**Comment by jm6087** [comment]
Additional information from Lisa on Discord

> He added an option to show shields on ramps. I want an option to not highlight ramps that shouldn't have shields.
![image](https://user-images.githubusercontent.com/24948653/116944430-1dec3780-ac3b-11eb-911e-f1a843030e82.png)

> Those shouldn't have shields and I don't want the highlight to tell me that they maybe should.

**Comment by jm6087** [comment]
I figured out one way to solve the issue (or part of it, I am not sure if I can think of all the variations

Changing         if (name && name.includes(abbr)) {
to               if (name && name.startsWith(abbr)) {

will only look at segments that start with abbr instead of contains it. 

I am trying to think of a case where it should "contain" abbr

**Comment by SkiDooGuy** [comment]
Already done with the current "Include Ramps" option. I moved the option to a higher level section to show the more general assoctiation.
